name: "chat-app"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5000:5000"  # Express
      - "8080:8080"  # Vite
    volumes:
      - .:/usr/app:cached

    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: ["pnpm", "run", "dev"]
