name: "chat-app"
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: .
      dockerfile: chat-client/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./chat-client:/app
      - /app/node_modules
